# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2026 callmetango for SonicDE

name: Build Package

on:
  workflow_call:
    inputs:
      repository:
        description: |-
          Location of the GitHub repository containing the package descriptions
          in the form of [HOST/]OWNER/REPO.
        type: string
        default: ${{ vars.PACKAGES_REPOSITORY }}
      branch:
        description: The branch to build
        type: string
        required: true
      package:
        description: |-
          The name of the package to build. Must be a subdirectory of the repository.
        type: string
        required: true
      packager:
        type: string
        description: >
          The builder of the packages in the form of a name and an email address in
          the form of John Doe <john@example.com>
        default: ${{ vars.PACKAGER }}
      docker-image:
        description: The name of the docker image to use
        type: string
        default: ${{ vars.DOCKER_IMAGE }}
      build-needed:
        description: |-
          Force the build of the package. Replaces an eventually existing package
          with the result of this build run.
        type: boolean

      # App-based authentication
      app-id:
        description: GitHub App Client ID
        type: string
        default: ${{ vars.APP_CLIENT_ID }}

      # PGP key handling
      pgp-key:
        description: PGP key file to use for verifying packages
        type: string
        default: ${{ vars.RELEASE_SIGNING_PUBLIC_KEY }}
    secrets:
      APP_PRIVATE_KEY:
        description: GitHub App private key
      RELEASE_SIGNING_KEY:
        description: The OpenPGP key to sign the packages
      RELEASE_SIGNING_KEY_PASSWORD:
        description: The password of the signing key

defaults:
  run:
    shell: sh

env:
  APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
  CARCH: x86_64 # TODO make configurable
  GH_TOKEN: ${{ github.token }}

jobs:
  build-package:
    runs-on: ubuntu-24.04
    steps:
      - name: Setup workspace
        uses: callmetango/setup-workspace@HEAD
        with:
          inputs: ${{ toJSON(inputs) }}
          vars: ${{ toJSON(vars) }}

      - name: Setup package build
        run: |
          . setup-build-env.sh
          setup-package-build.sh pkgbuilds/"$PACKAGE"

      - name: Build packages
        if: ${{ env.BUILD_NEEDED == 'true' }}
        uses: callmetango/archlinux-build-package-action@next
        with:
          path: pkgbuilds/${{ inputs.package }}
          packager: ${{ inputs.packager }}
          docker-image: ${{ inputs.docker-image }}
          makepkg-opts: --syncdeps --noconfirm
          srcinfo: false
          pgp-key: ${{ inputs.pgp-key }}
          signing-key: ${{ secrets.RELEASE_SIGNING_KEY }}
          signing-key-password: ${{ secrets.RELEASE_SIGNING_KEY_PASSWORD }}
          custom-repo-name: ${{ env.STAGING_REPO_NAME }}
          custom-repo-url: ${{ env.STAGING_REPO_URL }}
          custom-repo-siglevel: Optional TrustAll
          ninja: true
          tmpfs: true

      - name: Add packages to release
        if: ${{ env.BUILD_NEEDED == 'true' }}
        run: |
          . setup-build-env.sh # reauthenticate
          add-package-to-release.sh "$REPOSITORY" "$STAGING_TAG" \
              "$REPO_DB_NAME" pkgbuilds/"$PACKAGE"
