# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2026 callmetango for SonicDE.org

name: Build All and Publish

on:
  workflow_dispatch:
    inputs:
      build-needed:
        description: Force the build of all packages
        type: boolean
        default: false
      branch:
        description: The branch to build
        type: choice
        options:
          - beta
          - master
        default: master

defaults:
  run:
    shell: sh

env:
  CARCH: x86_64

jobs:
  _setup:
    runs-on: ubuntu-24.04
    steps:
      - name: Setup workspace
        uses: callmetango/setup-workspace@HEAD
        with:
          inputs: ${{ toJSON(inputs) }}
          vars: ${{ toJSON(vars) }}

      - name: Draft new release
        env:
          APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
        run: |
          . setup-build-env.sh
          draft-new-release.sh "$REPOSITORY" "$STAGING_TAG" "$BUILD_NEEDED"

  sonic-activities:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-core-addons
    with:
      package: sonic-activities
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-activities-stats:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-activities
      - sonic-frameworks-cmake-modules
    with:
      package: sonic-activities-stats
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-audio-applet-pulse:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-core-addons
      - sonic-frameworks-doctools
      - sonic-frameworks-keybind
      - sonic-frameworks-quick-ui
      - sonic-frameworks-quick-ui-addons
      - sonic-interface-libraries
      - sonic-workspace
    with:
      package: sonic-audio-applet-pulse
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-bluetooth-runtime:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-core-addons
      - sonic-frameworks-doctools
      - sonic-frameworks-io
      - sonic-frameworks-quick-ui
      - sonic-frameworks-windowsystem
      - sonic-interface-libraries
    with:
      package: sonic-bluetooth-runtime
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-breeze:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-decoration
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-color-scheme
      - sonic-frameworks-core-addons
      - sonic-frameworks-gui-addons
      - sonic-frameworks-icon-themes
      - sonic-frameworks-quick-ui
      - sonic-frameworks-windowsystem
    with:
      package: sonic-breeze
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-browser-integration:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-activities
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-core-addons
      - sonic-frameworks-io
      - sonic-workspace
    with:
      package: sonic-browser-integration
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-decoration:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
    with:
      package: sonic-decoration
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-desktop-interface:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-activities
      - sonic-activities-stats
      - sonic-frameworks-auth
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-core-addons
      - sonic-frameworks-doctools
      - sonic-frameworks-gui-addons
      - sonic-frameworks-icon-themes
      - sonic-frameworks-io
      - sonic-frameworks-keybind
      - sonic-frameworks-open-collab
      - sonic-frameworks-quick-ui
      - sonic-frameworks-quick-ui-addons
      - sonic-frameworks-runner
      - sonic-frameworks-settings-ui
      - sonic-frameworks-windowsystem
      - sonic-interface-libraries
      - sonic-system-monitor-library
      - sonic-win
      - sonic-workspace
    with:
      package: sonic-desktop-interface
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-dr-robotnik:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-core-addons
      - sonic-frameworks-idle-tracker
      - sonic-frameworks-io
      - sonic-frameworks-quick-ui
      - sonic-frameworks-windowsystem
    with:
      package: sonic-dr-robotnik
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-ecco:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-color-scheme
      - sonic-frameworks-core-addons
      - sonic-frameworks-doctools
      - sonic-frameworks-gui-addons
      - sonic-frameworks-icon-themes
      - sonic-frameworks-io
      - sonic-frameworks-io-extras
      - sonic-frameworks-settings-ui
      - sonic-frameworks-windowsystem
    with:
      package: sonic-ecco
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-frameworks-auth:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-core-addons
      - sonic-frameworks-windowsystem
    with:
      package: sonic-frameworks-auth
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-frameworks-cmake-modules:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
    with:
      package: sonic-frameworks-cmake-modules
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-frameworks-color-scheme:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-gui-addons
    with:
      package: sonic-frameworks-color-scheme
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-frameworks-core-addons:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
    with:
      package: sonic-frameworks-core-addons
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-frameworks-doctools:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
    with:
      package: sonic-frameworks-doctools
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-frameworks-gui-addons:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
    with:
      package: sonic-frameworks-gui-addons
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-frameworks-icon-themes:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-color-scheme
      - sonic-frameworks-silver-icons
    with:
      package: sonic-frameworks-icon-themes
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-frameworks-idle-tracker:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
    with:
      package: sonic-frameworks-idle-tracker
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-frameworks-io:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-color-scheme
      - sonic-frameworks-core-addons
      - sonic-frameworks-doctools
      - sonic-frameworks-gui-addons
      - sonic-frameworks-icon-themes
      - sonic-frameworks-windowsystem
    with:
      package: sonic-frameworks-io
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-frameworks-io-extras:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-activities
      - sonic-activities-stats
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-core-addons
      - sonic-frameworks-doctools
      - sonic-frameworks-io
    with:
      package: sonic-frameworks-io-extras
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-frameworks-io-fuse:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-core-addons
      - sonic-frameworks-io
    with:
      package: sonic-frameworks-io-fuse
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-frameworks-keybind:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
    with:
      package: sonic-frameworks-keybind
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-frameworks-open-collab:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
    with:
      package: sonic-frameworks-open-collab
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-frameworks-quick-silver-style:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-color-scheme
      - sonic-frameworks-gui-addons
      - sonic-frameworks-icon-themes
      - sonic-frameworks-quick-ui
    with:
      package: sonic-frameworks-quick-silver-style
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-frameworks-quick-ui:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
    with:
      package: sonic-frameworks-quick-ui
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-frameworks-quick-ui-addons:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-color-scheme
      - sonic-frameworks-core-addons
      - sonic-frameworks-gui-addons
      - sonic-frameworks-icon-themes
      - sonic-frameworks-keybind
      - sonic-frameworks-quick-ui
    with:
      package: sonic-frameworks-quick-ui-addons
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-frameworks-runner:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-core-addons
      - sonic-frameworks-doctools
      - sonic-frameworks-windowsystem
    with:
      package: sonic-frameworks-runner
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-frameworks-settings-ui:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-color-scheme
      - sonic-frameworks-core-addons
    with:
      package: sonic-frameworks-settings-ui
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-frameworks-silver-icons:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
    with:
      package: sonic-frameworks-silver-icons
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-frameworks-windowsystem:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
    with:
      package: sonic-frameworks-windowsystem
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-gtk-theme-bridge:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-decoration
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-color-scheme
      - sonic-frameworks-core-addons
      - sonic-frameworks-gui-addons
      - sonic-frameworks-windowsystem
    with:
      package: sonic-gtk-theme-bridge
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-interface-libraries:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-activities
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-color-scheme
      - sonic-frameworks-core-addons
      - sonic-frameworks-doctools
      - sonic-frameworks-gui-addons
      - sonic-frameworks-icon-themes
      - sonic-frameworks-io
      - sonic-frameworks-keybind
      - sonic-frameworks-quick-ui
      - sonic-frameworks-windowsystem
    with:
      package: sonic-interface-libraries
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-keybind-daemon:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-core-addons
      - sonic-frameworks-io
      - sonic-frameworks-keybind
      - sonic-frameworks-windowsystem
    with:
      package: sonic-keybind-daemon
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-login-manager:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-auth
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-core-addons
      - sonic-frameworks-io
      - sonic-frameworks-quick-ui
      - sonic-frameworks-windowsystem
      - sonic-interface-libraries
      - sonic-screen-library
      - sonic-workspace
    with:
      package: sonic-login-manager
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-network-manager:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-color-scheme
      - sonic-frameworks-core-addons
      - sonic-frameworks-io
      - sonic-frameworks-quick-ui
      - sonic-frameworks-quick-ui-addons
      - sonic-frameworks-windowsystem
      - sonic-interface-libraries
      - sonic-workspace
    with:
      package: sonic-network-manager
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-night-light:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-core-addons
    with:
      package: sonic-night-light
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-pipewire:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-core-addons
    with:
      package: sonic-pipewire
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-qt-theme-bridge:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-color-scheme
      - sonic-frameworks-core-addons
      - sonic-frameworks-gui-addons
      - sonic-frameworks-icon-themes
      - sonic-frameworks-io
      - sonic-frameworks-windowsystem
    with:
      package: sonic-qt-theme-bridge
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-quick-image-editor:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-quick-ui
    with:
      package: sonic-quick-image-editor
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-screen:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-core-addons
      - sonic-frameworks-quick-ui
      - sonic-frameworks-windowsystem
      - sonic-interface-libraries
      - sonic-screen-library
    with:
      package: sonic-screen
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-screen-library:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
    with:
      package: sonic-screen-library
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-screenies:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-core-addons
      - sonic-frameworks-doctools
      - sonic-frameworks-gui-addons
      - sonic-frameworks-io
      - sonic-frameworks-keybind
      - sonic-frameworks-quick-ui
      - sonic-frameworks-settings-ui
      - sonic-frameworks-windowsystem
      - sonic-pipewire
      - sonic-quick-image-editor
    with:
      package: sonic-screenies
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-screenlocker:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-core-addons
      - sonic-frameworks-doctools
      - sonic-frameworks-io
      - sonic-frameworks-keybind
      - sonic-frameworks-quick-ui
      - sonic-frameworks-windowsystem
      - sonic-interface-libraries
      - sonic-screen-library
    with:
      package: sonic-screenlocker
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-silver:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-decoration
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-core-addons
      - sonic-frameworks-gui-addons
      - sonic-frameworks-quick-ui
      - sonic-frameworks-silver-icons
      - sonic-frameworks-windowsystem
    with:
      package: sonic-silver
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-silver-gtk:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
      - sonic-silver
    with:
      package: sonic-silver-gtk
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-silver-sddm:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-workspace
    with:
      package: sonic-silver-sddm
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-system-info:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-auth
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-core-addons
      - sonic-frameworks-doctools
      - sonic-frameworks-io
      - sonic-frameworks-quick-ui
    with:
      package: sonic-system-info
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-system-monitor-library:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-auth
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-core-addons
      - sonic-frameworks-quick-ui
    with:
      package: sonic-system-monitor-library
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-terminal:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-color-scheme
      - sonic-frameworks-core-addons
      - sonic-frameworks-doctools
      - sonic-frameworks-gui-addons
      - sonic-frameworks-icon-themes
      - sonic-frameworks-io
      - sonic-frameworks-keybind
      - sonic-frameworks-settings-ui
      - sonic-frameworks-windowsystem
    with:
      package: sonic-terminal
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-terminal-tools:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-core-addons
      - sonic-frameworks-doctools
      - sonic-frameworks-icon-themes
      - sonic-frameworks-io
      - sonic-frameworks-windowsystem
    with:
      package: sonic-terminal-tools
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-welcome-center:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-core-addons
      - sonic-frameworks-io
      - sonic-frameworks-quick-ui
      - sonic-frameworks-windowsystem
      - sonic-interface-libraries
      - sonic-network-manager
    with:
      package: sonic-welcome-center
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-win:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-activities
      - sonic-decoration
      - sonic-frameworks-auth
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-color-scheme
      - sonic-frameworks-core-addons
      - sonic-frameworks-doctools
      - sonic-frameworks-gui-addons
      - sonic-frameworks-idle-tracker
      - sonic-frameworks-keybind
      - sonic-frameworks-quick-ui
      - sonic-frameworks-windowsystem
      - sonic-interface-libraries
      - sonic-keybind-daemon
      - sonic-night-light
      - sonic-screenlocker
      - sonic-silver
    with:
      package: sonic-win
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-workspace:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-activities
      - sonic-activities-stats
      - sonic-frameworks-auth
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-color-scheme
      - sonic-frameworks-core-addons
      - sonic-frameworks-doctools
      - sonic-frameworks-gui-addons
      - sonic-frameworks-icon-themes
      - sonic-frameworks-idle-tracker
      - sonic-frameworks-io
      - sonic-frameworks-io-extras
      - sonic-frameworks-io-fuse
      - sonic-frameworks-keybind
      - sonic-frameworks-quick-ui
      - sonic-frameworks-quick-ui-addons
      - sonic-frameworks-runner
      - sonic-frameworks-settings-ui
      - sonic-frameworks-windowsystem
      - sonic-interface-libraries
      - sonic-night-light
      - sonic-pipewire
      - sonic-screenlocker
      - sonic-system-monitor-library
      - sonic-terminal-tools
      - sonic-win
    with:
      package: sonic-workspace
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-workspace-addons:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-auth
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-core-addons
      - sonic-frameworks-gui-addons
      - sonic-frameworks-icon-themes
      - sonic-frameworks-io
      - sonic-frameworks-keybind
      - sonic-frameworks-quick-ui
      - sonic-frameworks-quick-ui-addons
      - sonic-frameworks-runner
      - sonic-frameworks-windowsystem
      - sonic-interface-libraries
      - sonic-win
      - sonic-workspace
    with:
      package: sonic-workspace-addons
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonic-workspace-wallpapers:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
    with:
      package: sonic-workspace-wallpapers
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  sonicde-meta:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-activities-stats
      - sonic-audio-applet-pulse
      - sonic-bluetooth-runtime
      - sonic-browser-integration
      - sonic-desktop-interface
      - sonic-dr-robotnik
      - sonic-ecco
      - sonic-frameworks-quick-silver-style
      - sonic-gtk-theme-bridge
      - sonic-login-manager
      - sonic-network-manager
      - sonic-night-light
      - sonic-pipewire
      - sonic-qt-theme-bridge
      - sonic-screen
      - sonic-screenies
      - sonic-silver
      - sonic-silver-gtk
      - sonic-system-info
      - sonic-terminal
      - sonic-terminal-tools
      - sonic-welcome-center
      - sonic-workspace-addons
      - xdg-desktop-portal-sonicde
    with:
      package: sonicde-meta
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  xdg-desktop-portal-sonicde:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-core-addons
      - sonic-frameworks-icon-themes
      - sonic-frameworks-io
      - sonic-frameworks-keybind
      - sonic-frameworks-quick-ui
      - sonic-frameworks-windowsystem
      - sonic-pipewire
      - sonic-workspace
    with:
      package: xdg-desktop-portal-sonicde
      branch: ${{ inputs.branch }}
      build-needed: ${{ inputs.build-needed }}
    secrets: inherit

  all-packages:
    runs-on: ubuntu-24.04
    needs:
      - sonic-activities
      - sonic-activities-stats
      - sonic-audio-applet-pulse
      - sonic-bluetooth-runtime
      - sonic-breeze
      - sonic-browser-integration
      - sonic-decoration
      - sonic-desktop-interface
      - sonic-dr-robotnik
      - sonic-ecco
      - sonic-frameworks-auth
      - sonic-frameworks-cmake-modules
      - sonic-frameworks-color-scheme
      - sonic-frameworks-core-addons
      - sonic-frameworks-doctools
      - sonic-frameworks-gui-addons
      - sonic-frameworks-icon-themes
      - sonic-frameworks-idle-tracker
      - sonic-frameworks-io
      - sonic-frameworks-io-extras
      - sonic-frameworks-io-fuse
      - sonic-frameworks-keybind
      - sonic-frameworks-open-collab
      - sonic-frameworks-quick-silver-style
      - sonic-frameworks-quick-ui
      - sonic-frameworks-quick-ui-addons
      - sonic-frameworks-runner
      - sonic-frameworks-settings-ui
      - sonic-frameworks-silver-icons
      - sonic-frameworks-windowsystem
      - sonic-gtk-theme-bridge
      - sonic-interface-libraries
      - sonic-keybind-daemon
      - sonic-login-manager
      - sonic-network-manager
      - sonic-night-light
      - sonic-pipewire
      - sonic-qt-theme-bridge
      - sonic-quick-image-editor
      - sonic-screen
      - sonic-screen-library
      - sonic-screenies
      - sonic-screenlocker
      - sonic-silver
      - sonic-silver-gtk
      - sonic-silver-sddm
      - sonic-system-info
      - sonic-system-monitor-library
      - sonic-terminal
      - sonic-terminal-tools
      - sonic-welcome-center
      - sonic-win
      - sonic-workspace
      - sonic-workspace-addons
      - sonic-workspace-wallpapers
      - sonicde-meta
      - xdg-desktop-portal-sonicde
    steps:
      - name: Setup workspace
        uses: callmetango/setup-workspace@HEAD
        with:
          inputs: ${{ toJSON(inputs) }}
          vars: ${{ toJSON(vars) }}

      - name: Release new release
        env:
          APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
        run: |
          create_repo_db=1; delete_source=1
          . setup-build-env.sh
          copy-release.sh "$REPOSITORY" "$STAGING_TAG" \
              "$REPOSITORY" "$CURRENT_TAG" $create_repo_db $delete_source
